# The Docker image that will be used to build your app
image: ubuntu:latest

# Define os estágios (fases) da sua pipeline
stages:
  - deploy

# Define o job 'create-pages' que pertence ao estágio 'deploy'
create-pages:
  stage: deploy
  script:
    - apt-get update
    - apt-get install -y git wget unzip
    - git clone https://github.com/flutter/flutter.git --depth 1 -b stable
    - export PATH="$PATH:$(pwd)/flutter/bin"
    - flutter --version
    - flutter pub get
    - flutter build web
  artifacts:
    paths:
      - build/web
  only:
    - main